### ISSUE TITLE
module federation throw error in HMR

### ISSUE THREAD

**Issue by ckken** [module-federation/module-federation-examples#138]
https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/126#event-3495597479
https://github.com/WebHotelier/webpack-fast-refresh/issues/5

**Comment by ScriptedAlchemy** [comment]
beta 20?

**Comment by ckken** [comment]
****

> beta 20?

yes

**Comment by ScriptedAlchemy** [comment]
@jherr what are you using for HMR? 

Worst case, live-reload works haha. I'll have to dig deeper. It might be good to post the issue here. Also, state how long its been an issue (beta 16?) 

https://github.com/webpack/webpack/issues/10352

**Comment by ckken** [comment]
revert to webpack5-beta-16 every thing goes well

**Comment by ScriptedAlchemy** [comment]
Should be resolved

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/86719669-dca8ec80-c056-11ea-93eb-7782a98e124f.png)
update webpack 5 beta 21

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/86720065-3dd0c000-c057-11ea-9784-4a3c8e04ffc4.png)
![image](https://user-images.githubusercontent.com/3890513/86720097-45906480-c057-11ea-8de7-65cc18f66322.png)

**Comment by shaodahong** [comment]
Still have

![image](https://user-images.githubusercontent.com/14831261/91942528-ae315000-ed2d-11ea-8fb3-a4e3c22f15e2.png)

Version info

```
"webpack": "^5.0.0-beta.29",
"@pmmmwh/react-refresh-webpack-plugin": "^0.4.1",
"webpack-cli": "^3.3.12",
"webpack-dev-server": "^3.11.0",
```

Plugin config

```js
      new ModuleFederationPlugin({
        name: APP_CONFIG.syscode,
        remotes,
        filename: 'remoteEntry.js',
        exposes: {
          './routes': './src/routes',
        },
      }),
```

**Comment by oschade** [comment]
Still an issue for me with the same error as above. Here the critical content in my remoteEntry.js:

![grafik](https://user-images.githubusercontent.com/19870969/103076523-3635b100-45ce-11eb-89d5-f69febfb5cd9.png)

**Comment by vjsolanki** [comment]
any update this ? 

I have created small sample to reproduce the error:
https://github.com/solankivj/fast-refresh-hmr-error

**Error only come when i expose something**

1. Try running app after clone with `npm start`
2. Edit something and save.
3. Error will show in console
4. Remove expose field from module_federation plugin and restart
5. Now the error is gone but on save we get full page refresh

**Comment by zedford** [comment]
I have this exact same issue that is only solved by not exposing anything in the ModuleFederationPlugin. Looks like cross-container support is on the roadmap:
https://github.com/module-federation/module-federation-examples/issues/358
